from __future__ import annotations

DEFAULT_BASE_URL = "https://open.feishu.cn/open-apis"
DEFAULT_TIMEOUT_SECONDS = 30.0
DEFAULT_OAUTH_CALLBACK_HOST = "127.0.0.1"
DEFAULT_OAUTH_CALLBACK_PORT = 18080
DEFAULT_OAUTH_CALLBACK_PATH = "/callback"
DEFAULT_USER_TOKEN_REFRESH_BEFORE_SECONDS = 300.0
